// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/accounts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页查询账号",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "账号列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "注册新账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "创建账号",
                "parameters": [
                    {
                        "description": "账号信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/accounts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据 ID 查询账号",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "获取账号详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新账号昵称、头像、角色或状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "更新账号",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "软删除账号",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "删除账号",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/asr": {
            "post": {
                "description": "提交公网音频 URL，同步返回豆包 ASR 完整识别结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "语音识别"
                ],
                "summary": "同步语音识别",
                "parameters": [
                    {
                        "description": "音频 URL",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ASRRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "使用用户名和密码登录，校验通过后返回 JWT Token 及用户信息。本接口无需鉴权。登录失败（用户名不存在、密码错误、账号被禁用）统一返回 401，避免泄露账号是否存在。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户名密码登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误（如缺少 username 或 password）",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误，或账号已被禁用",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/chat": {
            "post": {
                "description": "提交系统/用户提示词，同步返回上游 LLM 的完整 Chat Completions 结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大模型对话"
                ],
                "summary": "同步大模型对话",
                "parameters": [
                    {
                        "description": "对话请求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ChatRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/live-materials": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页查询直播素材，支持日期与关键词筛选，不含 live_asr / asr_summaries；keywords/asr_keywords 支持 \",\"=与、\"|\"=或；asr_keywords 匹配 asr_paragraphs 并返回 matched_paragraphs；列表项含 project_count，默认每页 10 条",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "直播素材列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始日期 YYYY-MM-DD",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 YYYY-MM-DD",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "标题关键词：\\",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ASR 段落关键词：\\",
                        "name": "asr_keywords",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "添加一条直播素材，name、live_url 为必填；url_type 由后台按 live_url 自动识别写入",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "创建直播素材",
                "parameters": [
                    {
                        "description": "素材信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateLiveMaterialRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "409": {
                        "description": "素材已存在，code=40901，data 为已有记录",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/live-materials/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据 ID 查询直播素材完整信息；live_asr 为分句数组；含 asr_summaries（AI 主题分段）与 asr_paragraphs（全文段落划分）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "获取直播素材详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "素材 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "仅可编辑 name、remark，其它字段不可修改",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "更新直播素材",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "素材 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateLiveMaterialRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "物理删除直播素材，并级联删除 video_project 中关联的剪辑项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "删除直播素材",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "素材 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/live-materials/{id}/asr/retry": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "仅 asr_status=failed 时可重试：重置为 pending，由后台 Worker 扫库自动执行",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "重新 ASR",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "素材 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/live-materials/{id}/asr/subtitle": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回 TXT：关键词取自 asr_summaries.title；文字记录分段与 asr_paragraphs 完全一致（说话人 / start_time / text），显示为「说话人${speaker}」；仅 asr_status=completed 且 asr_paragraphs 非空时可下载",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "下载 ASR 字幕",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "素材 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ASR 字幕 TXT 文件",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/live-materials/{id}/video-projects": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页查询指定直播素材关联的剪辑项目；列表项同时返回 live_id、live_name 与 task_count；素材不存在时 404",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "素材关联的剪辑项目列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "素材 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/llm-system-prompts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页查询系统提示词，支持关键词与日期筛选，列表返回完整 content；created_by 为创建人展示名",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大模型系统提示词"
                ],
                "summary": "系统提示词列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键词：\\",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始日期 YYYY-MM-DD",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 YYYY-MM-DD",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "添加一条系统提示词，创建人取自 JWT 当前用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大模型系统提示词"
                ],
                "summary": "创建系统提示词",
                "parameters": [
                    {
                        "description": "提示词信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateLLMSystemPromptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/llm-system-prompts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据 ID 查询系统提示词完整信息（含 content）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大模型系统提示词"
                ],
                "summary": "获取系统提示词详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "提示词 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "更新 name、content、remark、ext；is_editable=0 的预置提示词不可修改",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大模型系统提示词"
                ],
                "summary": "更新系统提示词",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "提示词 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateLLMSystemPromptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "物理删除系统提示词；is_editable=0 的预置提示词不可删除",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大模型系统提示词"
                ],
                "summary": "删除系统提示词",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "提示词 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页查询异步任务，支持按 type、status、创建日期与关键词筛选；keywords 支持 \",\"=与、\"|\"=或，模糊匹配 task.video_project_name；列表项含 video_project_name、live_url、live_name、clips_tar_url、width/height（创建时按 video_project 自动快照）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "异步任务"
                ],
                "summary": "任务列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务类型：ai_slice / draft / ai_slice_draft",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "任务状态：pending / processing / completed / failed",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始日期 YYYY-MM-DD，按 created_at 筛选",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 YYYY-MM-DD，按 created_at 筛选",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词：\\",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/tasks/ai-slice": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "异步：按 video_project.prompt_id 加载系统提示词，用 clips0 时间段从 live_asr 筛选句段组装用户提示词，LLM 返回句段索引后回写 video_project.clips1；立即返回 task，请轮询 GET /v1/tasks/:id 查看 status/progress",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "异步任务"
                ],
                "summary": "创建 AI 切片任务",
                "parameters": [
                    {
                        "description": "任务参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateAISliceTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/tasks/ai-slice-draft": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "异步：等价于先执行 AI 切片（按 clips0 筛选 ASR、LLM 选索引写 clips1）再执行剪映草稿（create_draft 画布取请求 canvas_*，否则用 video_project.width/height，创建时写入 task.width/height/live_url）并回写 task.draft_url，成功后继续 gen_video 回写 task.video_url（视频失败仍保留 draft_url，任务标记 completed）；立即返回 task，请轮询 GET /v1/tasks/:id 查看 status/progress/draft_url/video_url",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "异步任务"
                ],
                "summary": "创建一键成片任务",
                "parameters": [
                    {
                        "description": "任务参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateAISliceDraftTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/tasks/draft": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "异步：根据 video_project.id 读取 live_material.live_url 与 video_project.clips1，ffmpeg 精确裁剪后调用 capcut-mate create_draft（画布取请求 canvas_*，否则用 video_project.width/height，创建时写入 task.width/height/live_url）生成剪映草稿并回写 task.draft_url，成功后继续 gen_video 回写 task.video_url（视频失败仍保留 draft_url，任务标记 completed）；立即返回 task，请轮询 GET /v1/tasks/:id 查看 status/progress/draft_url/video_url",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "异步任务"
                ],
                "summary": "创建剪映草稿任务",
                "parameters": [
                    {
                        "description": "任务参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateDraftTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/tasks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据 ID 查询任务；直接读取数据库中的 status、progress、draft_url、video_url、clips_tar_url、width/height/live_url/live_name 等字段，用于轮询异步任务进度；created_by 为创建人展示名",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "异步任务"
                ],
                "summary": "获取任务详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务 ID（UUID）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/video-projects": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分页查询剪辑项目，支持关键词与日期筛选；列表项同时返回 live_id、live_name（关联 live_material.name）与 task_count（关联 task 总数）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "剪辑项目"
                ],
                "summary": "剪辑项目列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键词：\\",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始日期 YYYY-MM-DD",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 YYYY-MM-DD",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "添加一条剪辑项目，创建人取自 JWT 当前用户；clips0/clips1 为可选 JSON 数组；enable_captions 可选（bool，默认 true）；width/height 可选，仅支持 1920×1080 或 1080×1920，不传时按关联素材分辨率自动选更接近的一档；成功后返回完整项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "剪辑项目"
                ],
                "summary": "创建剪辑项目",
                "parameters": [
                    {
                        "description": "项目信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateVideoProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/video-projects/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据 ID 查询剪辑项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "剪辑项目"
                ],
                "summary": "获取剪辑项目详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "仅更新请求中显式传入且合法的字段（name/remark/prompt_id/clips0/clips1/width/height/project_source/enable_captions）；未传字段保持不变；若传 width/height 须成对且仅为 1920×1080 或 1080×1920；enable_captions 为 bool，入库为 0/1",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "剪辑项目"
                ],
                "summary": "更新剪辑项目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateVideoProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "物理删除剪辑项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "剪辑项目"
                ],
                "summary": "删除剪辑项目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v1/video-projects/{id}/running-tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "返回指定剪辑项目下未结束的任务（默认 pending + processing）；active_only=true 时仅返回 processing；可选按 type 筛选；返回 task 全字段（created_by 为展示名）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "异步任务"
                ],
                "summary": "查询项目运行中的任务",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "剪辑项目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "任务类型：ai_slice / draft / ai_slice_draft",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "仅返回 processing 状态",
                        "name": "active_only",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        },
        "/v2/accounts/{id}/profile": {
            "get": {
                "description": "v2 版本账号概要接口",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号-v2"
                ],
                "summary": "获取账号简要信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Body"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ClipRange": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                }
            }
        },
        "model.ClipWithText": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "words": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ClipWord"
                    }
                }
            }
        },
        "model.ClipWord": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "response.Body": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.ASRRequest": {
            "type": "object",
            "required": [
                "audio_url"
            ],
            "properties": {
                "audio_url": {
                    "type": "string"
                }
            }
        },
        "v1.ChatRequest": {
            "type": "object",
            "required": [
                "usr_prompt"
            ],
            "properties": {
                "sys_prompt": {
                    "description": "SysPrompt 系统提示词，可选，默认为空。",
                    "type": "string"
                },
                "usr_prompt": {
                    "description": "UsrPrompt 用户提示词，必选。",
                    "type": "string"
                }
            }
        },
        "v1.CreateAISliceDraftTaskRequest": {
            "type": "object",
            "required": [
                "video_project_id"
            ],
            "properties": {
                "canvas_height": {
                    "type": "integer"
                },
                "canvas_width": {
                    "type": "integer"
                },
                "video_project_id": {
                    "type": "integer"
                }
            }
        },
        "v1.CreateAISliceTaskRequest": {
            "type": "object",
            "required": [
                "video_project_id"
            ],
            "properties": {
                "video_project_id": {
                    "type": "integer"
                }
            }
        },
        "v1.CreateAccountRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "avatar": {
                    "description": "用户头像 URL",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "roles": {
                    "description": "用户角色，多个角色用逗号分隔",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.CreateDraftTaskRequest": {
            "type": "object",
            "required": [
                "video_project_id"
            ],
            "properties": {
                "canvas_height": {
                    "type": "integer"
                },
                "canvas_width": {
                    "type": "integer"
                },
                "video_project_id": {
                    "type": "integer"
                }
            }
        },
        "v1.CreateLLMSystemPromptRequest": {
            "type": "object",
            "required": [
                "content",
                "name"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "ext": {
                    "type": "string",
                    "maxLength": 1024
                },
                "name": {
                    "type": "string",
                    "maxLength": 128
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "v1.CreateLiveMaterialRequest": {
            "type": "object",
            "required": [
                "live_url",
                "name"
            ],
            "properties": {
                "ext": {
                    "type": "string",
                    "maxLength": 1024
                },
                "live_url": {
                    "type": "string",
                    "maxLength": 1024
                },
                "name": {
                    "type": "string",
                    "maxLength": 64
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "v1.CreateVideoProjectRequest": {
            "type": "object",
            "required": [
                "live_id",
                "name"
            ],
            "properties": {
                "clips0": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ClipRange"
                    }
                },
                "clips1": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ClipWithText"
                    }
                },
                "enable_captions": {
                    "description": "是否添加字幕；未传默认 true，入库为 0/1",
                    "type": "boolean"
                },
                "height": {
                    "type": "integer",
                    "minimum": 0
                },
                "live_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64
                },
                "project_source": {
                    "description": "项目来源，未传默认为空",
                    "type": "string",
                    "maxLength": 32
                },
                "prompt_id": {
                    "description": "提示词 ID，未传或为 0 时默认 1",
                    "type": "integer"
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                },
                "width": {
                    "description": "Width / Height 可选：仅支持 1920×1080 或 1080×1920；都不传时按素材分辨率自动选档。",
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "v1.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "v1.LoginResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "https://cdn.example.com/avatar/1.jpg"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 7200
                },
                "id": {
                    "type": "string",
                    "example": "1"
                },
                "nickname": {
                    "type": "string",
                    "example": "管理员"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "ADMIN"
                    ]
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "v1.UpdateAccountRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "可选，用户头像 URL",
                    "type": "string"
                },
                "is_active": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "roles": {
                    "description": "可选，用户角色，多个角色用逗号分隔",
                    "type": "string"
                }
            }
        },
        "v1.UpdateLLMSystemPromptRequest": {
            "type": "object",
            "required": [
                "content",
                "name"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "ext": {
                    "type": "string",
                    "maxLength": 1024
                },
                "name": {
                    "type": "string",
                    "maxLength": 128
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "v1.UpdateLiveMaterialRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 64
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "v1.UpdateVideoProjectRequest": {
            "type": "object",
            "properties": {
                "clips0": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ClipRange"
                    }
                },
                "clips1": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ClipWithText"
                    }
                },
                "enable_captions": {
                    "description": "是否添加字幕；入库为 0/1",
                    "type": "boolean"
                },
                "height": {
                    "type": "integer",
                    "minimum": 0
                },
                "name": {
                    "type": "string",
                    "maxLength": 64
                },
                "project_source": {
                    "type": "string",
                    "maxLength": 32
                },
                "prompt_id": {
                    "type": "integer"
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                },
                "width": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:30000",
	BasePath:         "/openapi/live-mixer",
	Schemes:          []string{},
	Title:            "Base API",
	Description:      "基于 Gin + PostgreSQL 的基础 API 服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
