// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/accounts": {
            "get": {
                "description": "分页查询账号",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "账号列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "post": {
                "description": "注册新账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "创建账号",
                "parameters": [
                    {
                        "description": "账号信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_v1.CreateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/v1/accounts/{id}": {
            "get": {
                "description": "根据 ID 查询账号",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "获取账号详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "put": {
                "description": "更新账号昵称、头像、角色或状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "更新账号",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_v1.UpdateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "delete": {
                "description": "软删除账号",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号"
                ],
                "summary": "删除账号",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/v1/asr": {
            "post": {
                "description": "提交公网音频 URL，同步返回豆包 ASR 完整识别结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "语音识别"
                ],
                "summary": "同步语音识别",
                "parameters": [
                    {
                        "description": "音频 URL",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_v1.ASRRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "post": {
                "description": "使用用户名和密码登录，校验通过后返回 JWT Token 及用户信息。本接口无需鉴权。登录失败（用户名不存在、密码错误、账号被禁用）统一返回 401，避免泄露账号是否存在。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户名密码登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_v1.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/live-mixer_pkg_response.Body"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_handler_v1.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误（如缺少 username 或 password）",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "用户名或密码错误，或账号已被禁用",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/v1/live-materials": {
            "get": {
                "description": "分页查询直播素材，支持日期与关键词筛选，不含 live_asr 字段，默认每页 10 条",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "直播素材列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "开始日期 YYYY-MM-DD",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 YYYY-MM-DD",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "标题关键词，英文逗号分隔，匹配 name/remark",
                        "name": "title_keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "全局关键词，英文逗号分隔，匹配 live_url/asr_error_msg/name/remark",
                        "name": "global_keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "post": {
                "description": "添加一条直播素材，name、live_url 为必填",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "创建直播素材",
                "parameters": [
                    {
                        "description": "素材信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_v1.CreateLiveMaterialRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/v1/live-materials/{id}": {
            "get": {
                "description": "根据 ID 查询直播素材完整信息（含 live_asr）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "获取直播素材详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "素材 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "put": {
                "description": "仅可编辑 name、remark，其它字段不可修改",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "更新直播素材",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "素材 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_v1.UpdateLiveMaterialRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "delete": {
                "description": "物理删除直播素材，并级联删除 video_project 中关联的剪辑项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "直播素材"
                ],
                "summary": "删除直播素材",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "素材 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/v1/llm-system-prompts": {
            "get": {
                "description": "分页查询系统提示词，支持关键词与日期筛选，列表返回完整 content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大模型系统提示词"
                ],
                "summary": "系统提示词列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键词，英文逗号分隔，匹配 name/content/remark",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始日期 YYYY-MM-DD",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 YYYY-MM-DD",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "post": {
                "description": "添加一条系统提示词，创建人取自 JWT 当前用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大模型系统提示词"
                ],
                "summary": "创建系统提示词",
                "parameters": [
                    {
                        "description": "提示词信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_v1.CreateLLMSystemPromptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/v1/llm-system-prompts/{id}": {
            "get": {
                "description": "根据 ID 查询系统提示词完整信息（含 content）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大模型系统提示词"
                ],
                "summary": "获取系统提示词详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "提示词 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "put": {
                "description": "更新 name、content、remark、ext；is_editable=0 的预置提示词不可修改",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大模型系统提示词"
                ],
                "summary": "更新系统提示词",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "提示词 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_v1.UpdateLLMSystemPromptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "delete": {
                "description": "物理删除系统提示词；is_editable=0 的预置提示词不可删除",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "大模型系统提示词"
                ],
                "summary": "删除系统提示词",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "提示词 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/v1/video-projects": {
            "get": {
                "description": "分页查询剪辑项目，支持关键词与日期筛选",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "剪辑项目"
                ],
                "summary": "剪辑项目列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键词，英文逗号分隔，匹配 name/remark",
                        "name": "keywords",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始日期 YYYY-MM-DD",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束日期 YYYY-MM-DD",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "post": {
                "description": "添加一条剪辑项目，创建人取自 JWT 当前用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "剪辑项目"
                ],
                "summary": "创建剪辑项目",
                "parameters": [
                    {
                        "description": "项目信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_v1.CreateVideoProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/v1/video-projects/{id}": {
            "get": {
                "description": "根据 ID 查询剪辑项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "剪辑项目"
                ],
                "summary": "获取剪辑项目详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "put": {
                "description": "更新 name、remark、clips0、clips1、draft_url、video_url，未传字段保持不变",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "剪辑项目"
                ],
                "summary": "更新剪辑项目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_v1.UpdateVideoProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            },
            "delete": {
                "description": "物理删除剪辑项目",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "剪辑项目"
                ],
                "summary": "删除剪辑项目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            }
        },
        "/v2/accounts/{id}/profile": {
            "get": {
                "description": "v2 版本账号概要接口",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号-v2"
                ],
                "summary": "获取账号简要信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/live-mixer_pkg_response.Body"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handler_v1.ASRRequest": {
            "type": "object",
            "required": [
                "audio_url"
            ],
            "properties": {
                "audio_url": {
                    "type": "string"
                }
            }
        },
        "internal_handler_v1.CreateAccountRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "avatar": {
                    "description": "用户头像 URL",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "roles": {
                    "description": "用户角色，多个角色用逗号分隔",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_handler_v1.CreateLLMSystemPromptRequest": {
            "type": "object",
            "required": [
                "content",
                "name"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "ext": {
                    "type": "string",
                    "maxLength": 1024
                },
                "name": {
                    "type": "string",
                    "maxLength": 128
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "internal_handler_v1.CreateLiveMaterialRequest": {
            "type": "object",
            "required": [
                "live_url",
                "name"
            ],
            "properties": {
                "ext": {
                    "type": "string",
                    "maxLength": 1024
                },
                "live_url": {
                    "type": "string",
                    "maxLength": 1024
                },
                "name": {
                    "type": "string",
                    "maxLength": 64
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "internal_handler_v1.CreateVideoProjectRequest": {
            "type": "object",
            "required": [
                "live_id",
                "name"
            ],
            "properties": {
                "clips0": {
                    "type": "string"
                },
                "clips1": {
                    "type": "string"
                },
                "live_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 64
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "internal_handler_v1.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "internal_handler_v1.LoginResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string",
                    "example": "https://cdn.example.com/avatar/1.jpg"
                },
                "expires_in": {
                    "type": "integer",
                    "example": 7200
                },
                "id": {
                    "type": "string",
                    "example": "1"
                },
                "nickname": {
                    "type": "string",
                    "example": "管理员"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "ADMIN"
                    ]
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "internal_handler_v1.UpdateAccountRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "可选，用户头像 URL",
                    "type": "string"
                },
                "is_active": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "roles": {
                    "description": "可选，用户角色，多个角色用逗号分隔",
                    "type": "string"
                }
            }
        },
        "internal_handler_v1.UpdateLLMSystemPromptRequest": {
            "type": "object",
            "required": [
                "content",
                "name"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "ext": {
                    "type": "string",
                    "maxLength": 1024
                },
                "name": {
                    "type": "string",
                    "maxLength": 128
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "internal_handler_v1.UpdateLiveMaterialRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 64
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                }
            }
        },
        "internal_handler_v1.UpdateVideoProjectRequest": {
            "type": "object",
            "properties": {
                "clips0": {
                    "type": "string"
                },
                "clips1": {
                    "type": "string"
                },
                "draft_url": {
                    "type": "string",
                    "maxLength": 1024
                },
                "name": {
                    "type": "string",
                    "maxLength": 64
                },
                "remark": {
                    "type": "string",
                    "maxLength": 256
                },
                "video_url": {
                    "type": "string",
                    "maxLength": 1024
                }
            }
        },
        "live-mixer_pkg_response.Body": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:30000",
	BasePath:         "/openapi/live-mixer",
	Schemes:          []string{},
	Title:            "Base API",
	Description:      "基于 Gin + PostgreSQL 的基础 API 服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
